name: Daily URL GET (01:00 Beijing Time)

on:
  schedule:
    - cron: "0 17 * * *"   # UTC 17:00 = 北京时间 01:00
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 35   # 整个 job 最长 35 分钟
    steps:
      - name: GET two URLs with status logs
        env:
          URL1: ${{ secrets.PING_URL1 }}
          URL2: ${{ secrets.PING_URL2 }}
        run: |
          set -euo pipefail
          failures=0

          hit() {
            local url="$1"
            echo "==> Hitting: $url"
            code=$(curl -sS -o /dev/null -w "%{http_code}" \
              --retry 1 --max-time 1800 \
              -H 'Cache-Control: no-cache' \
              -A 'GH-Actions-Pinger/1.0' \
              "$url" || echo "000")
            echo "HTTP $code"
            if [ "$code" -lt 200 ] || [ "$code" -ge 400 ]; then
              echo "!! Request failed for $url"
              failures=$((failures+1))
            fi
            echo
          }

          hit "$URL1"
          hit "$URL2"

          if [ "$failures" -gt 0 ]; then
            echo "There were $failures failed request(s)."
            exit 1
          else
            echo "All requests succeeded."
          fi
